### ISSUE TITLE
关于代码输出的问题

### ISSUE THREAD

**Issue by wujm7** [yhao-z/TMNN#1]
您好 谢谢作者的分享! 您的这篇工作我非常感兴趣，所以试图跑了一下代码。 但是有一些不明白的地方。
我想问一下 为什么我运行了以后想用imshow(x)查看输出的恢复图片，得到的是一张特别淡的MRI图呢，只有隐隐约约的一些图像痕迹，看不清楚，我该怎么得到论文中那种清晰的恢复图像呢？然后该如何计算PSNR和SSIM呀？

**Comment by yhao-z** [comment]
* 首先，imshow(x)是MATLAB自动[0,1]区间展示图像，而我们的图像经过归一化之后最大值为1，因此可能有很大一部分像素值显示的比较暗。你可以通过调整imshow的区间来更好的显示图像，例如`imshow(x, [0, 0.2])`。详情可参考MATLAB函数帮助。
* 其次，我们论文中并没有计算PSNR和SSIM，所以本代码不包含此函数。
  > PSNR的计算可以参考[此函数](https://github.com/yhao-z/dMRI-utils/blob/master/PSNR.m)以及[MATLAB自带psnr函数](https://github.com/TaiXiangJiang/reproducible-tensor-completion-state-of-the-art)
  > SSIM可参考[此函数](http://[www.cns.nyu.edu/~lcv/ssim/ssim_index.m](http://www.cns.nyu.edu/~lcv/ssim/ssim_index.m))
